name: 01 - Building Blocks
on: 
#  push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hola, Mundo"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Succesful Step
        run: |
          echo "I will fail"
          exit 0
      - name: Say Goodbye
        run: echo "Adiós, Mundo"
