name: 03-WorflowRunners
on:
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: | 
          echo "This Job is running from ubuntu-latest"
          echo ${{ runner.os }}
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: | 
          echo "This Job is running from windows-latest"
          echo ${{ runner.os }}
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: | 
          echo "This Job is running from mac-latest"
          echo ${{ runner.os }}
