name: 04 - Using Actions
on: 
  push:

jobs:
  Checkout_Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
  Printing_Folders:
    runs-on: ubuntu-latest
    steps:
      - name: Print Folders
        run: ls -la
